travis:
  secure:
    BINSTAR_TOKEN: GH4imGJl+iV7yRr5QCaON+1/SllS3espFFV0f5tLNSrCtAC8I93ssqWnpJysKfggRAkPZRv1s2q6gsSjmm4TaIoIBGMFplSrBBSnbE4EuC9hpwUlsulRZevJjvCQTVDQ/GB5aAAxZOXhuxzZnILYLsk3O/dMAw1NQG8wXjeyaQ1zL4Px+HFfZD56zVpcMfULwcSqTkY74xctFEZdxqgAPBkBLHTA5AFdMyqYaBhF5frqdWFoKCm2kJfqTQdJjcuU13rl60Eq/Fixv/BBW9USvTHIEQstbOPlUbEaiRmZ8dGCWQ1pEJIPyyTeektm6g2zl0mR8nWovMHIiUbTeUQLD6LyH31jpXKOjA1ykUpBf4M0eiY0B0p53Nc1Zw1qGTd41x8ZGWFjTKgj9va6iAaOG01dRHU9ShhGKR+8qQWGaW/aVYHSWwsa68DInqr7kR8mB+tWJ9IUi1wwyp9J2Wxy1ooP7UfP7+1aO5NAhtcqaKJ/e22YV5LecxkXNemT4jQQycSEXjbKUFwJuVSVBIy9ltMFyCDgMmTsIUJW5pplDa8g5zRkDnGNpA9xaBK8zbykeEbysJlYsSwBVv/WPN03CcjEZbiLHpL3IyUaH4BOf239bXEqfnGK4N22bFJmLqYbBHQ+1FUxTSD6xzwXMgAhNX3NPFz0TQKhDyA1oyfqTmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
